apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: monit
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/OperatingOpenShift/monit/releases/download/v0.1.0/monit_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./monit"
      to: "."
    - from: LICENSE
      to: "."
    bin: "monit"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/OperatingOpenShift/monit/releases/download/v0.1.0/monit_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./monit"
      to: "."
    - from: LICENSE
      to: "."
    bin: "monit"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/OperatingOpenShift/monit/releases/download/v0.1.0/monit_windows_amd64.zip
    sha256: ""
    files:
    - from: "/monit.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "monit.exe"
  shortDescription: A new plugin
  homepage: https://github.com/OperatingOpenShift/monit
  caveats: |
    Usage:
      $ kubectl monit

    For additional options:
      $ kubectl monit --help
      or https://github.com/OperatingOpenShift/monit/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
